version: "3.9"

services:
  backend:
    depends_on:
      - dind
      - db
      - nginx-git
    build:
      context: ./backend
      dockerfile: Dockerfile # use the Dev.Dockerfile for development
    volumes:
      #- ./backend:/app # allows reloading of code
      - ./data/:/app/data/
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=value
    restart: "unless-stopped"

  db:
    image: mongo
    logging:
      driver: none
    restart: "unless-stopped"

  dind:
    image: docker:dind
    privileged: true
    entrypoint: dockerd --host=tcp://0.0.0.0:80 --tls=false
    logging:
      driver: none
    restart: "unless-stopped"

  nginx-git:
    image: catks/gitserver-http:0.1.0-rc.3-2-g117e58d
    user: 1000:1000
    logging:
      driver: none
    volumes:
      - /data/git:/home/git
    restart: "unless-stopped"

  frontend:
    build: ./frontend
    logging:
      driver: none
    restart: "unless-stopped"

  reverseproxy:
    depends_on:
      - backend
      - frontend
    image: nginx:alpine
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    logging:
      driver: none
    restart: "unless-stopped"
