version: "3.3"

services:
  backend:
    depends_on:
      - dind
      - db
      - nginx-git
    build:
      context: ./backend
      dockerfile: Dev.Dockerfile # use the Dev.Dockerfile for development
    volumes:
      - ./backend:/app # allows reloading of code
      - ./data/:/app/data/
    ports:
      - 3000:3000
    restart: "unless-stopped"
    networks:
      - vuln

  db:
    image: mongo
    logging:
      driver: none
    restart: "unless-stopped"
    networks:
      - vuln

  dind:
    image: docker:dind
    privileged: true
    entrypoint: dockerd --host=tcp://0.0.0.0:80 --tls=false
    logging:
      driver: none
    restart: "unless-stopped"
    tmpfs:
      - /var/run/
    networks:
      - vuln

  nginx-git:
    image: catks/gitserver-http:0.1.0-rc.3-2-g117e58d
    user: 1000:1000
    logging:
      driver: none
    volumes:
      - ./data/git:/home/git
    restart: "unless-stopped"
    networks:
      - vuln

  frontend:
    build: ./frontend
    logging:
      driver: none
    restart: "unless-stopped"
    networks:
      - vuln

  reverseproxy:
    depends_on:
      - backend
      - frontend
    image: nginx:alpine
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    logging:
      driver: none
    restart: "unless-stopped"
    networks:
      - vuln

networks:
  vuln:
    external: true
