version: "3.3"

services:
  backend:
    container_name: underleaf-backend
    depends_on:
      - dind
      - db
      - nginx-git
      - permission-fixer
    build:
      context: ./backend
      dockerfile: Dev.Dockerfile # use the Dev.Dockerfile for development
    volumes:
      - ./backend:/app # allows reloading of code
      - ./data/:/app/data/
      - docker-cert:/cert
    ports:
      - 3000:3000
    env_file:
      - env.env

    restart: "unless-stopped"

  db:
    image: mongo
    logging:
      driver: none
    env_file:
      - env.env
    restart: "unless-stopped"
    command: --auth

  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    logging:
      driver: none
    restart: "unless-stopped"
    tmpfs:
      - /var/run/
    volumes:
      - docker-cert:/certs

  nginx-git:
    image: catks/gitserver-http:0.1.0-rc.3-2-g117e58d
    user: 1000:1000
    depends_on:
      - permission-fixer
    logging:
      driver: none
    volumes:
      - ./data/git:/home/git
    restart: "unless-stopped"

  frontend:
    build: ./frontend
    logging:
      driver: none
    restart: "unless-stopped"

  reverseproxy:
    depends_on:
      - backend
      - frontend
    image: nginx:alpine
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4242:4242
    logging:
      driver: none
    restart: "unless-stopped"

  permission-fixer:
    image: alpine
    command:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /data/git/; mkdir -p /data/projects/; chown -R 1000:1000 /data",
      ]
    volumes:
      - ./data/:/data

  cleaner:
    image: alpine
    command: ["/bin/sh", "-c", "while true; do find /data/git/* /data/projects/* /data/compile/* -maxdepth 1 -type d -mmin +20 -exec rm -rv {} +; echo 'Cleaned old projects'; sleep 1200; done"]
    volumes:
      - ./data/:/data

volumes:
  docker-cert:
