version: "3"

services:
  underleaf-checker:
    container_name: underleaf-checker
    build: .
    ports:
      - 4243:8000
      - 4244:4244
      - 4245:4245
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=underleaf-checker-db
      - MONGO_PORT=27017
      - MONGO_USER=underleaf_checker_user
      - MONGO_PASSWORD=underleaf_checker_password
      - NOT_ENOCHECKER_TEST=${NOT_ENOCHECKER_TEST}
      - CHECKER_IP=${CHECKER_IP}

  underleaf-checker-db:
    image: mongo
    volumes:
      - underleaf-checker-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: underleaf_checker_user
      MONGO_INITDB_ROOT_PASSWORD: underleaf_checker_password
    logging:
      driver: none

volumes:
  underleaf-checker-db:
